# Generated by Django 3.2.23 on 2024-01-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_mywallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywallet',
            name='default_card_number',
            field=models.CharField(blank=True, default=123, max_length=16, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mywallet',
            name='default_cvv_number',
            field=models.IntegerField(blank=True, default=1234, unique=True),
            preserve_default=False,
        ),
    ]
