# Generated by Django 3.2.23 on 2024-03-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20240328_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywallet',
            name='cvv_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mywallet',
            name='expire_number',
            field=models.DateField(blank=True, null=True),
        ),
    ]
