# Generated by Django 3.2.23 on 2024-01-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20240128_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywallet',
            name='default_expire_number',
            field=models.DateField(),
        ),
    ]
