# Generated by Django 3.2.23 on 2024-01-28 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_mywallet_default_expire_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mywallet',
            old_name='default_card_number',
            new_name='card_number',
        ),
        migrations.RenameField(
            model_name='mywallet',
            old_name='default_cvv_number',
            new_name='cvv_number',
        ),
        migrations.RenameField(
            model_name='mywallet',
            old_name='default_expire_number',
            new_name='expire_number',
        ),
    ]
