# Generated by Django 3.2.23 on 2024-02-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20240128_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywallet',
            name='expire_number',
            field=models.DateField(blank=True),
        ),
    ]
