# Generated by Django 3.2.23 on 2024-02-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_mywallet_expire_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='mywallet',
            name='name',
            field=models.CharField(blank=True, max_length=16, unique=True),
        ),
    ]
