# Generated by Django 3.2.23 on 2024-03-28 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20240328_0854'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishlistTable',
        ),
    ]
