# Generated by Django 3.2.23 on 2024-03-27 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_commenttable_reviewtable_wishlisttable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='comment',
            new_name='review_content',
        ),
        migrations.DeleteModel(
            name='ReviewTable',
        ),
    ]
