# Generated by Django 3.2.23 on 2024-03-28 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20240327_1859'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishlistTable',
        ),
    ]
